In [ ]:
!pip install numpy

In [ ]:
import numpy as np

Section A (Q.1-11)

In [ ]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [ ]:
arr2=np.array((1,2,3,4,5))
arr2

array([1, 2, 3, 4, 5])

In [ ]:
mydict = {'a':1, 'b': 2, 'c':3}
arr3 =np.array(list(mydict.values()))
arr3

array([1, 2, 3])

In [ ]:
import pandas as pd
pandaSeries=pd.Series([10,20,30,40,50])
convertedNp = pandaSeries.to_numpy()
convertedNp

array([10, 20, 30, 40, 50])

In [ ]:
arr4 = np.array([[1,2,4,],[1,3,1]])
arr4.shape


(2, 3)

In [ ]:
zeroes_1d=np.array([0,0,0,0,0,0,0,0,0,0])
zeroes_1d

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr_2d = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
arr_2d.shape

(3, 4)